// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY0kJQcWvHx2raQPPSwr8qe43BFI5Vwx8',
    appId: '1:167198755812:web:544083ede8a512d489d5f1',
    messagingSenderId: '167198755812',
    projectId: 'auto-rent-cdd02',
    authDomain: 'auto-rent-cdd02.firebaseapp.com',
    storageBucket: 'auto-rent-cdd02.firebasestorage.app',
    measurementId: 'G-NNTY8505T3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhQVA2BuAvx4RxJqqFcAHK_f8StauCEOs',
    appId: '1:167198755812:android:413395fb4c13a41e89d5f1',
    messagingSenderId: '167198755812',
    projectId: 'auto-rent-cdd02',
    storageBucket: 'auto-rent-cdd02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRvs8iwi09YkwUkrNNA6B3AKSbMu3Y0DA',
    appId: '1:167198755812:ios:2d506d442a07083689d5f1',
    messagingSenderId: '167198755812',
    projectId: 'auto-rent-cdd02',
    storageBucket: 'auto-rent-cdd02.firebasestorage.app',
    iosBundleId: 'com.example.autoRent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRvs8iwi09YkwUkrNNA6B3AKSbMu3Y0DA',
    appId: '1:167198755812:ios:2d506d442a07083689d5f1',
    messagingSenderId: '167198755812',
    projectId: 'auto-rent-cdd02',
    storageBucket: 'auto-rent-cdd02.firebasestorage.app',
    iosBundleId: 'com.example.autoRent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCY0kJQcWvHx2raQPPSwr8qe43BFI5Vwx8',
    appId: '1:167198755812:web:e544c8683613516189d5f1',
    messagingSenderId: '167198755812',
    projectId: 'auto-rent-cdd02',
    authDomain: 'auto-rent-cdd02.firebaseapp.com',
    storageBucket: 'auto-rent-cdd02.firebasestorage.app',
    measurementId: 'G-6J5VTY72M0',
  );
}
